version: '3'
services:
  db:
    image: postgres
    container_name: demo-db
    volumes:
      - database:/var/lib/postgresql/data
      - ./dev/postgres-init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
  redis:
    container_name: demo-redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: password
  pgadmin:
    container_name: demo-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: team@demo.dev
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'
    volumes:
      - ./dev/pgadmin/servers.json:/pgadmin4/servers.json
      - ./dev/pgadmin/pgpassfile:/pgadmin4/pgpassfile
volumes:
  database:
